name: Deploy Static Website with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Build the Docker Image
      - name: Build Docker Image
        run: docker build -t static-website .

      # Step 3: Run the Container
      - name: Run Docker Container
        run: |
          docker run -d -p 8080:80 static-website
          sleep 10

      # Step 4: Debug Container
      - name: Check Running Containers
        run: docker ps

      - name: Output Container Logs
        run: docker logs $(docker ps -q -f ancestor=static-website)

      # Step 5: Test the Website
      - name: Test Docker Container
        run: |
          curl -v http://127.0.0.1:8080 || exit 1
