name: Deploy Static Website with Docker and GitHub Pages

on:
  push:
    branches:
      - main  # Run the workflow only for pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Build the Docker Image
      - name: Build Docker Image
        run: |
          docker build -t static-website .

      # Step 3: Test the Docker Container
      - name: Test Docker Container
        run: |
          docker run -d -p 8080:80 static-website
          curl --fail http://localhost:8080 || exit 1

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
